name: Test Report, Checkstyle, SpotBugs, Notify Codecov CI

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Run Test and Send Report
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Docker run
        run: docker compose up -d

      - name: Grant execute permission to gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        id: test
        run: ./gradlew test
        if: always()

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Run check style
        id: checkstyle
        uses: nikitasavinov/checkstyle-action@master
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'testtool'
          level: error
          checkstyle_config: 'config/checkstyle/checkstyle.xml'
          workdir: 'src/main'

      - name: Run SpotBugs
        id: spotbugs
        run: ./gradlew spotbugsMain
        if: always()

      - name: Upload SpotBugs Report
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: test results
          path: build/reports/spotbugs/main.html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: always()

      - name: Discord Message Notify
        uses: appleboy/discord-action@0.0.3
        with:
          webhook_id: ${{ secrets.WEBHOOK_ID }}
          webhook_token: ${{ secrets.WEBHOOK_TOKEN }}
          color: "#48f442"
          username: "GitHub Bot"
          args: "The ${{ github.event_name }} event triggered."
